export const sections = [
    {
        id: 'id_LOGO', // isActive: false,
        name: 'LOGO', url: '/',
    },
    {
        id: 'id_Men', // isActive: false,
        name: 'Men', url: 'path/men',
    },
    {
        id: 'id_Women', // isActive: false,
        name: 'Women', url: 'path/women',
    },
    {
        id: 'id_Kids', // isActive: false,
        name: 'Kids', url: 'path/kids',
    },
    {
        id: 'id_Sale', // isActive: false,
        name: 'Sale', url: 'path/sale',
    },
    {
        id: 'id_Collections', // isActive: false,
        name: 'Collections', url: 'path/collections',
    },
    {
        id: 'id_Blog', // isActive: false,
        name: 'Blog', url: 'path/blog',
    },
    {
        id: 'id_Theme', // isActive: false,
        name: 'Theme', url: 'path/theme', items: [
            {
                id: 'id_item_light', // isActive: false,
                name: 'light', url: 'path/light',
            },
            {
                id: 'id_item_dark', // isActive: false,
                name: 'dark', url: 'path/dark',
            },
            {
                id: 'id_item_moon', // isActive: false,
                name: 'moon', url: 'path/moon',
            },
        ],
    },
];

export const DEFAULT_SECTION = 'all';
export const DEFAULT_COLLECTION = 'all';
export const DEFAULT_APPAREL = 'all';

export type TypeMenuItemDTO = {
    id: string;
    name: string;
    prefixPath: string;
    path: string;
    subMenu: Array<TypeMenuItemDTO> | null;
}
export type TypeExtendedMenuItem = {
    [key in Exclude<keyof TypeMenuItemDTO, 'subMenu'>]: string;
} & {
    isActive: boolean;
    subMenu: Array<TypeExtendedMenuItem> | null;
}

export const tempMenuItems: TypeMenuItemDTO = {
    id: 'id_menu',
    name: 'LOGO',
    prefixPath: '',
    path: '/',
    subMenu: [
        {
            id: 'id_Men',
            name: 'Men',
            prefixPath: '',
            path: 'men', subMenu: [
                {
                    id: 'id_1.1.1',
                    name: '1.1.1',
                    prefixPath: '',
                    path: 'collections1_1_1',
                    subMenu: [
                        {
                            id: 'id_1.1.1.1',
                            name: '1.1.1.1',
                            prefixPath: '',
                            path: 'id_1_1_1_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.1.1.2',
                            name: '1.1.1.2',
                            prefixPath: '',
                            path: 'id_1_1_1_2',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_1.1.2',
                    name: '1.1.2',
                    prefixPath: '',
                    path: 'collections1_1_2',
                    subMenu: [
                        {
                            id: 'id_1.1.2.1',
                            name: '1.1.2.1',
                            prefixPath: '',
                            path: 'id_1_1_2_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.1.2.2',
                            name: '1.1.2.2',
                            prefixPath: '',
                            path: 'id_1_1_2_2',
                            subMenu: null,
                        },
                    ],
                },
            ],
        },
    ],
}

export const menuItems: TypeMenuItemDTO = {
    id: 'id_menu',
    name: 'LOGO',
    prefixPath: '',
    path: '',
    subMenu: [
        {
            id: 'id_Men',
            name: 'Men',
            prefixPath: '',
            path: 'men', subMenu: [
                {
                    id: 'id_1.1.1',
                    name: '1.1.1',
                    prefixPath: '',
                    path: 'collections1_1_1',
                    subMenu: [
                        {
                            id: 'id_1.1.1.1',
                            name: '1.1.1.1',
                            prefixPath: '',
                            path: 'id_1_1_1_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.1.1.2',
                            name: '1.1.1.2',
                            prefixPath: '',
                            path: 'id_1_1_1_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.1.1.3',
                            name: '1.1.1.3',
                            prefixPath: '',
                            path: 'id_1_1_1_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.1.1.4',
                            name: '1.1.1.4',
                            prefixPath: '',
                            path: 'id_1_1_1_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_1.1.2',
                    name: '1.1.2',
                    prefixPath: '',
                    path: 'collections1_1_2',
                    subMenu: [
                        {
                            id: 'id_1.1.2.1',
                            name: '1.1.2.1',
                            prefixPath: '',
                            path: 'id_1_1_2_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.1.2.2',
                            name: '1.1.2.2',
                            prefixPath: '',
                            path: 'id_1_1_2_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.1.2.3',
                            name: '1.1.2.3',
                            prefixPath: '',
                            path: 'id_1_1_2_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.1.2.4',
                            name: '1.1.2.4',
                            prefixPath: '',
                            path: 'id_1_1_2_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_1.1.3',
                    name: '1.1.3',
                    prefixPath: '',
                    path: 'collections1_1_3',
                    subMenu: [
                        {
                            id: 'id_1.1.3.1',
                            name: '1.1.3.1',
                            prefixPath: '',
                            path: 'id_1_1_3_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.1.3.2',
                            name: '1.1.3.2',
                            prefixPath: '',
                            path: 'id_1_1_3_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.1.3.3',
                            name: '1.1.3.3',
                            prefixPath: '',
                            path: 'id_1_1_3_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.1.3.4',
                            name: '1.1.3.4',
                            prefixPath: '',
                            path: 'id_1_1_3_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_1.1.4',
                    name: '1.1.4',
                    prefixPath: '',
                    path: 'collections1_1_4',
                    subMenu: [
                        {
                            id: 'id_1.1.4.1',
                            name: '1.1.4.1',
                            prefixPath: '',
                            path: 'id_1_1_4_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.1.4.2',
                            name: '1.1.4.2',
                            prefixPath: '',
                            path: 'id_1_1_4_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.1.4.3',
                            name: '1.1.4.3',
                            prefixPath: '',
                            path: 'id_1_1_4_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.1.4.4',
                            name: '1.1.4.4',
                            prefixPath: '',
                            path: 'id_1_1_4_4',
                            subMenu: null,
                        },
                    ],
                },
            ],
        },
        {
            id: 'id_Women',
            name: 'Women',
            prefixPath: '',
            path: 'catalog',
            subMenu: [
                {
                    id: 'id_All',
                    name: 'All',
                    prefixPath: '',
                    path: 'products',
                    subMenu: [
                        {
                            id: 'id_1.2.1.1',
                            name: '1.2.1.1',
                            prefixPath: '',
                            path: 'id_1.2.1.1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.1.2',
                            name: '1.2.1.2',
                            prefixPath: '',
                            path: 'id_1.2.1.2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.1.3',
                            name: '1.2.1.3',
                            prefixPath: '',
                            path: 'id_1_2_1_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.1.4',
                            name: '1.2.1.4',
                            prefixPath: '',
                            path: 'id_1_2_1_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_Women_Collections',
                    name: 'Collections',
                    prefixPath: '',
                    path: 'catalog',
                    subMenu: [
                        {
                            id: 'id_Our_Favorites',
                            name: 'Our Favorites',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                        {
                            id: 'id_New_Arrivals',
                            name: 'New Arrivals',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                        {
                            id: 'id_New_Collections',
                            name: 'New Collections',
                            prefixPath: '',
                            path: 'catalog',
                            subMenu: null,
                        },
                        {
                            id: 'id_Brands',
                            name: 'Brands',
                            prefixPath: '',
                            path: 'catalog',
                            subMenu: [
                                {
                                    id: 'id_akris',
                                    name: 'Akris',
                                    prefixPath: '',
                                    path: 'products',
                                    subMenu: null,
                                },
                                {
                                    id: 'id_alice&olivia',
                                    name: 'Alice + Olivia',
                                    prefixPath: '',
                                    path: 'products',
                                    subMenu: null,
                                },
                                {
                                    id: 'id_brunello_cucinelli',
                                    name: 'Brunello Cucinelli',
                                    prefixPath: '',
                                    path: 'products',
                                    subMenu: null,
                                },
                                {
                                    id: 'id_chanel',
                                    name: 'CHANEL',
                                    prefixPath: '',
                                    path: 'products',
                                    subMenu: null,
                                },
                                {
                                    id: 'id_dolce&gabbana',
                                    name: 'Dolce & Gabbana',
                                    prefixPath: '',
                                    path: 'products',
                                    subMenu: null,
                                },
                                {
                                    id: 'id_eileen_fisher',
                                    name: 'Eileen Fisher',
                                    prefixPath: '',
                                    path: 'products',
                                    subMenu: null,
                                },
                                {
                                    id: 'id_giorgio_armani',
                                    name: 'Giorgio Armani',
                                    prefixPath: '',
                                    path: 'products',
                                    subMenu: null,
                                },
                                {
                                    id: 'id_gucci',
                                    name: 'Gucci',
                                    prefixPath: '',
                                    path: 'products',
                                    subMenu: null,
                                },
                                {
                                    id: 'id_johnny_was',
                                    name: 'Johnny Was',
                                    prefixPath: '',
                                    path: 'products',
                                    subMenu: null,
                                },
                                {
                                    id: 'id_lafayette_148_new_york',
                                    name: 'Lafayette 148 New York',
                                    prefixPath: '',
                                    path: 'products',
                                    subMenu: null,
                                },
                                {
                                    id: 'id_theory',
                                    name: 'Theory',
                                    prefixPath: '',
                                    path: 'products',
                                    subMenu: null,
                                },
                            ],
                        },
                        {
                            id: 'id_Trends',
                            name: 'Trends',
                            prefixPath: '',
                            path: 'catalog',
                            subMenu: null,
                        },
                        {
                            id: 'id_New_Names_at_Neiman`s',
                            name: 'New Names at Neiman`s',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                        {
                            id: 'id_luxe',
                            name: 'Luxe',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                        {
                            id: 'id_essentials',
                            name: 'Essentials',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                        {
                            id: 'id_exclusives',
                            name: 'Exclusives',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_Coats_&_Jackets',
                    name: 'Coats & Jackets',
                    prefixPath: '',
                    path: 'products',
                    subMenu: [
                        {
                            id: 'id_1.2.3.1',
                            name: '1.2.3.1',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.3.2',
                            name: '1.2.3.2',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.3.3',
                            name: '1.2.3.3',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.3.4',
                            name: '1.2.3.4',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_Dresses',
                    name: 'Dresses',
                    prefixPath: '',
                    path: 'products',
                    subMenu: [
                        {
                            id: 'id_1.2.4.1',
                            name: '1.2.4.1',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.4.2',
                            name: '1.2.4.2',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.4.3',
                            name: '1.2.4.3',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.4.4',
                            name: '1.2.4.4',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_Pants',
                    name: 'Pants',
                    prefixPath: '',
                    path: 'products',
                    subMenu: [
                        {
                            id: 'id_1.2.5.1',
                            name: '1.2.5.1',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.5.2',
                            name: '1.2.5.2',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.5.3',
                            name: '1.2.5.3',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.5.4',
                            name: '1.2.5.4',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_Jumpsuits_&_Rompers',
                    name: 'Jumpsuits & Rompers',
                    prefixPath: '',
                    path: 'products',
                    subMenu: [
                        {
                            id: 'id_1.2.6.1',
                            name: '1.2.6.1',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.6.2',
                            name: '1.2.6.2',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.6.3',
                            name: '1.2.6.3',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.6.4',
                            name: '1.2.6.4',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_Shorts',
                    name: 'Shorts',
                    prefixPath: '',
                    path: 'products',
                    subMenu: [
                        {
                            id: 'id_1.2.7.1',
                            name: '1.2.7.1',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.7.2',
                            name: '1.2.7.2',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.7.3',
                            name: '1.2.7.3',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.7.4',
                            name: '1.2.7.4',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_Skirts',
                    name: 'Skirts',
                    prefixPath: '',
                    path: 'products',
                    subMenu: [
                        {
                            id: 'id_1.2.8.1',
                            name: '1.2.8.1',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.8.2',
                            name: '1.2.8.2',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.8.3',
                            name: '1.2.8.3',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.8.4',
                            name: '1.2.8.4',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_Sweaters',
                    name: 'Sweaters',
                    prefixPath: '',
                    path: 'products',
                    subMenu: [
                        {
                            id: 'id_1.2.9.1',
                            name: '1.2.9.1',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.9.2',
                            name: '1.2.9.2',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.9.3',
                            name: '1.2.9.3',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.9.4',
                            name: '1.2.9.4',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_Swimwear',
                    name: 'Swimwear',
                    prefixPath: '',
                    path: 'products',
                    subMenu: [
                        {
                            id: 'id_1.2.10.1',
                            name: '1.2.10.1',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.10.2',
                            name: '1.2.10.2',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.10.3',
                            name: '1.2.10.3',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.10.4',
                            name: '1.2.10.4',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_Tops',
                    name: 'Tops',
                    prefixPath: '',
                    path: 'products',
                    subMenu: [
                        {
                            id: 'id_1.2.11.1',
                            name: '1.2.11.1',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.11.2',
                            name: '1.2.11.2',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.11.3',
                            name: '1.2.11.3',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.11.4',
                            name: '1.2.11.4',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_Shoes',
                    name: 'Shoes',
                    prefixPath: '',
                    path: 'products',
                    subMenu: [
                        {
                            id: 'id_1.2.12.1',
                            name: '1.2.12.1',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.12.2',
                            name: '1.2.12.2',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.12.3',
                            name: '1.2.12.3',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.12.4',
                            name: '1.2.12.4',
                            prefixPath: '',
                            path: 'products',
                            subMenu: null,
                        },
                    ],
                },
            ],
        },
        {
            id: 'id_Kids',
            name: 'Kids',
            prefixPath: '',
            path: 'kids',
            subMenu: [
                {
                    id: 'id_1.3.1',
                    name: '1.3.1',
                    prefixPath: '',
                    path: 'collections_1_3_1',
                    subMenu: [
                        {
                            id: 'id_1.3.1.1',
                            name: '1.3.1.1',
                            prefixPath: '',
                            path: 'id_1_3_1_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.3.1.2',
                            name: '1.3.1.2',
                            prefixPath: '',
                            path: 'id_1_3_1_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.3.1.3',
                            name: '1.3.1.3',
                            prefixPath: '',
                            path: 'id_1_3_1_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.3.1.4',
                            name: '1.3.1.4',
                            prefixPath: '',
                            path: 'id_1_3_1_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_1.3.2',
                    name: '1.3.2',
                    prefixPath: '',
                    path: 'collections_1_3_2',
                    subMenu: [
                        {
                            id: 'id_1.3.2.1',
                            name: '1.3.2.1',
                            prefixPath: '',
                            path: 'id_1_3_2_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.3.2.2',
                            name: '1.3.2.2',
                            prefixPath: '',
                            path: 'id_1_3_2_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.3.2.3',
                            name: '1.3.2.3',
                            prefixPath: '',
                            path: 'id_1_3_2_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.3.2.4',
                            name: '1.3.2.4',
                            prefixPath: '',
                            path: 'id_1_3_2_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_1.3.3',
                    name: '1.3.3',
                    prefixPath: '',
                    path: 'collections_1_3_3',
                    subMenu: [
                        {
                            id: 'id_1.3.3.1',
                            name: '1.3.3.1',
                            prefixPath: '',
                            path: 'id_1_3_3_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.3.3.2',
                            name: '1.3.3.2',
                            prefixPath: '',
                            path: 'id_1_3_3_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.3.3.3',
                            name: '1.3.3.3',
                            prefixPath: '',
                            path: 'id_1_3_3_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.3.3.4',
                            name: '1.3.3.4',
                            prefixPath: '',
                            path: 'id_1_3_3_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_1.3.4',
                    name: '1.3.4',
                    prefixPath: '',
                    path: 'collections_1_3_4',
                    subMenu: [
                        {
                            id: 'id_1.3.4.1',
                            name: '1.3.4.1',
                            prefixPath: '',
                            path: 'id_1_3_4_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.3.4.2',
                            name: '1.3.4.2',
                            prefixPath: '',
                            path: 'id_1_3_4_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.3.4.3',
                            name: '1.3.4.3',
                            prefixPath: '',
                            path: 'id_1_3_4_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.3.4.4',
                            name: '1.3.4.4',
                            prefixPath: '',
                            path: 'id_1_3_4_4',
                            subMenu: null,
                        },
                    ],
                },
            ],
        },
        {
            id: 'id_Sale',
            name: 'Sale',
            prefixPath: '',
            path: 'sale',
            subMenu: [
                {
                    id: 'id_1.4.1',
                    name: '1.4.1',
                    prefixPath: '',
                    path: 'collections_1_4_1',
                    subMenu: [
                        {
                            id: 'id_1.4.1.1',
                            name: '1.4.1.1',
                            prefixPath: '',
                            path: 'id_1_4_1_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.4.1.2',
                            name: '1.4.1.2',
                            prefixPath: '',
                            path: 'id_1_4_1_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.4.1.3',
                            name: '1.4.1.3',
                            prefixPath: '',
                            path: 'id_1_4_1_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.4.1.4',
                            name: '1.4.1.4',
                            prefixPath: '',
                            path: 'id_1_4_1_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_1.4.2',
                    name: '1.4.2',
                    prefixPath: '',
                    path: 'collections_1_4_2',
                    subMenu: [
                        {
                            id: 'id_1.4.2.1',
                            name: '1.4.2.1',
                            prefixPath: '',
                            path: 'id_1_4_2_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.4.2.2',
                            name: '1.4.2.2',
                            prefixPath: '',
                            path: 'id_1_4_2_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.4.2.3',
                            name: '1.4.2.3',
                            prefixPath: '',
                            path: 'id_1_4_2_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.4.2.4',
                            name: '1.4.2.4',
                            prefixPath: '',
                            path: 'id_1_4_2_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_1.4.3',
                    name: '1.4.3',
                    prefixPath: '',
                    path: 'collections_1_4_3',
                    subMenu: [
                        {
                            id: 'id_1.4.3.1',
                            name: '1.4.3.1',
                            prefixPath: '',
                            path: 'id_1_4_3_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.4.3.2',
                            name: '1.4.3.2',
                            prefixPath: '',
                            path: 'id_1_4_3_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.4.3.3',
                            name: '1.4.3.3',
                            prefixPath: '',
                            path: 'id_1_4_3_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.4.3.4',
                            name: '1.4.3.4',
                            prefixPath: '',
                            path: 'id_1_4_3_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_1.4.4',
                    name: '1.4.4',
                    prefixPath: '',
                    path: 'collections_1_4_4',
                    subMenu: [
                        {
                            id: 'id_1.4.4.1',
                            name: '1.4.4.1',
                            prefixPath: '',
                            path: 'id_1_4_4_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.4.4.2',
                            name: '1.4.4.2',
                            prefixPath: '',
                            path: 'id_1_4_4_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.4.4.3',
                            name: '1.4.4.3',
                            prefixPath: '',
                            path: 'id_1_4_4_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.4.4.4',
                            name: '1.4.4.4',
                            prefixPath: '',
                            path: 'id_1_4_4_4',
                            subMenu: null,
                        },
                    ],
                },
            ],
        },
        {
            id: 'id_Collections',
            name: 'Collections',
            prefixPath: '',
            path: 'collections',
            subMenu: [
                {
                    id: 'id_1.5.1',
                    name: '1.5.1',
                    prefixPath: '',
                    path: 'collections_1_5_1',
                    subMenu: [
                        {
                            id: 'id_1.5.1.1',
                            name: '1.5.1.1',
                            prefixPath: '',
                            path: 'id_1_5_1_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.5.1.2',
                            name: '1.5.1.2',
                            prefixPath: '',
                            path: 'id_1_5_1_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.5.1.3',
                            name: '1.5.1.3',
                            prefixPath: '',
                            path: 'id_1_5_1_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.5.1.4',
                            name: '1.5.1.4',
                            prefixPath: '',
                            path: 'id_1_5_1_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_1.5.2',
                    name: '1.5.2',
                    prefixPath: '',
                    path: 'collections_1_5_2',
                    subMenu: [
                        {
                            id: 'id_1.5.2.1',
                            name: '1.5.2.1',
                            prefixPath: '',
                            path: 'id_1_5_2_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.5.2.2',
                            name: '1.5.2.2',
                            prefixPath: '',
                            path: 'id_1_5_2_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.5.2.3',
                            name: '1.5.2.3',
                            prefixPath: '',
                            path: 'id_1_5_2_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.5.2.4',
                            name: '1.5.2.4',
                            prefixPath: '',
                            path: 'id_1_5_2_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_1.5.3',
                    name: '1.5.3',
                    prefixPath: '',
                    path: 'collections_1_5_3',
                    subMenu: [
                        {
                            id: 'id_1.5.3.1',
                            name: '1.5.3.1',
                            prefixPath: '',
                            path: 'id_1_5_3_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.5.3.2',
                            name: '1.5.3.2',
                            prefixPath: '',
                            path: 'id_1_5_3_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.5.3.3',
                            name: '1.5.3.3',
                            prefixPath: '',
                            path: 'id_1_5_3_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.5.3.4',
                            name: '1.5.3.4',
                            prefixPath: '',
                            path: 'id_1_5_3_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_1.5.4',
                    name: '1.5.4',
                    prefixPath: '',
                    path: 'collections_1_5_4',
                    subMenu: [
                        {
                            id: 'id_1.5.4.1',
                            name: '1.5.4.1',
                            prefixPath: '',
                            path: 'id_1_5_4_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.5.4.2',
                            name: '1.5.4.2',
                            prefixPath: '',
                            path: 'id_1_5_4_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.5.4.3',
                            name: '1.5.4.3',
                            prefixPath: '',
                            path: 'id_1_5_4_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.5.4.4',
                            name: '1.5.4.4',
                            prefixPath: '',
                            path: 'id_1_5_4_4',
                            subMenu: null,
                        },
                    ],
                },
            ],
        },
        {
            id: 'id_Blog',
            name: 'Blog',
            prefixPath: '',
            path: 'blog',
            subMenu: [
                {
                    id: 'id_1.6.1',
                    name: '1.6.1',
                    prefixPath: '',
                    path: 'collections_1_6_1',
                    subMenu: [
                        {
                            id: 'id_1.6.1.1',
                            name: '1.6.1.1',
                            prefixPath: '',
                            path: 'id_1_6_1_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.6.1.2',
                            name: '1.6.1.2',
                            prefixPath: '',
                            path: 'id_1_6_1_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.6.1.3',
                            name: '1.6.1.3',
                            prefixPath: '',
                            path: 'id_1_6_1_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.6.1.4',
                            name: '1.6.1.4',
                            prefixPath: '',
                            path: 'id_1_6_1_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_1.6.2',
                    name: '1.6.2',
                    prefixPath: '',
                    path: 'collections_1_6_2',
                    subMenu: [
                        {
                            id: 'id_1.6.2.1',
                            name: '1.6.2.1',
                            prefixPath: '',
                            path: 'id_1_6_2_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.6.2.2',
                            name: '1.6.2.2',
                            prefixPath: '',
                            path: 'id_1_6_2_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.6.2.3',
                            name: '1.6.2.3',
                            prefixPath: '',
                            path: 'id_1_6_2_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.6.2.4',
                            name: '1.6.2.4',
                            prefixPath: '',
                            path: 'id_1_6_2_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_1.6.3',
                    name: '1.6.3',
                    prefixPath: '',
                    path: 'collections_1_6_3',
                    subMenu: [
                        {
                            id: 'id_1.6.3.1',
                            name: '1.6.3.1',
                            prefixPath: '',
                            path: 'id_1_6_3_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.6.3.2',
                            name: '1.6.3.2',
                            prefixPath: '',
                            path: 'id_1_6_3_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.6.3.3',
                            name: '1.6.3.3',
                            prefixPath: '',
                            path: 'id_1_6_3_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.6.3.4',
                            name: '1.6.3.4',
                            prefixPath: '',
                            path: 'id_1_6_3_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_1.6.4',
                    name: '1.6.4',
                    prefixPath: '',
                    path: 'collections_1_6_4',
                    subMenu: [
                        {
                            id: 'id_1.6.4.1',
                            name: '1.6.4.1',
                            prefixPath: '',
                            path: 'id_1_6_4_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.6.4.2',
                            name: '1.6.4.2',
                            prefixPath: '',
                            path: 'id_1_6_4_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.6.4.3',
                            name: '1.6.4.3',
                            prefixPath: '',
                            path: 'id_1_6_4_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.6.4.4',
                            name: '1.6.4.4',
                            prefixPath: '',
                            path: 'id_1_6_4_4',
                            subMenu: null,
                        },
                    ],
                },
            ],
        },
    ],
};