export const sections = [
    {id: 'id_LOGO', isActive: false, name: 'LOGO', url: '/'},
    {id: 'id_Men', isActive: false, name: 'Men', url: 'path/men'},
    {id: 'id_Women', isActive: false, name: 'Women', url: 'path/women'},
    {id: 'id_Kids', isActive: false, name: 'Kids', url: 'path/kids'},
    {id: 'id_Sale', isActive: false, name: 'Sale', url: 'path/sale'},
    {id: 'id_Collections', isActive: false, name: 'Collections', url: 'path/collections'},
    {id: 'id_Blog', isActive: false, name: 'Blog', url: 'path/blog'},
    {
        id: 'id_Theme', isActive: false, name: 'Theme', url: 'path/theme', items: [
            {id: 'id_item_light', isActive: false, name: 'light', url: 'path/light'},
            {id: 'id_item_dark', isActive: false, name: 'dark', url: 'path/dark'},
            {id: 'id_item_moon', isActive: false, name: 'moon', url: 'path/moon'},
        ],
    },
];

export const DEFAULT_SECTION = 'all';
export const DEFAULT_COLLECTION = 'all';
export const DEFAULT_APPAREL = 'all';

export type TypeMenuItem = {
    id: string;
    isActive: boolean;
    name: string;
    prefixPath: string;
    level:number;
    path: string;
    subMenu: Array<TypeMenuItem> | null;
}
export type TypeExtendedMenuItem = {
    [key in Exclude<keyof TypeMenuItem, 'subMenu'>]: string;
} & {
    isActive: boolean;
    subMenu: Array<TypeExtendedMenuItem> | null;
}

// export class

//Routing path: /section/
export const menuItems: TypeMenuItem = {
    id: 'id_menu',
    isActive: false,
    name: 'LOGO',
    prefixPath: 'products',
    level: 0,
    path: '/',
    subMenu: [
        {

            id: 'id_Men', isActive: false, name: 'Men', prefixPath: 'products',
            level: 0, path: 'men', subMenu: [
                {
                    id: 'id_1.1.1',
                    isActive: false,
                    name: '1.1.1',
                    prefixPath: 'products',
                    level: 1,
                    path: 'collections1_1_1',
                    subMenu: [
                        {
                            id: 'id_1.1.1.1',
                            isActive: false,
                            name: '1.1.1.1',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_1_1_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.1.1.2',
                            isActive: false,
                            name: '1.1.1.2',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_1_1_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.1.1.3',
                            isActive: false,
                            name: '1.1.1.3',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_1_1_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.1.1.4',
                            isActive: false,
                            name: '1.1.1.4',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_1_1_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_1.1.2',
                    isActive: false,
                    name: '1.1.2',
                    prefixPath: 'products',
                    level: 1,
                    path: 'collections1_1_2',
                    subMenu: [
                        {
                            id: 'id_1.1.2.1',
                            isActive: false,
                            name: '1.1.2.1',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_1_2_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.1.2.2',
                            isActive: false,
                            name: '1.1.2.2',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_1_2_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.1.2.3',
                            isActive: false,
                            name: '1.1.2.3',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_1_2_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.1.2.4',
                            isActive: false,
                            name: '1.1.2.4',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_1_2_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_1.1.3',
                    isActive: false,
                    name: '1.1.3',
                    prefixPath: 'products',
                    level: 1,
                    path: 'collections1_1_3',
                    subMenu: [
                        {
                            id: 'id_1.1.3.1',
                            isActive: false,
                            name: '1.1.3.1',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_1_3_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.1.3.2',
                            isActive: false,
                            name: '1.1.3.2',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_1_3_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.1.3.3',
                            isActive: false,
                            name: '1.1.3.3',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_1_3_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.1.3.4',
                            isActive: false,
                            name: '1.1.3.4',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_1_3_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_1.1.4',
                    isActive: false,
                    name: '1.1.4',
                    prefixPath: 'products',
                    level: 1,
                    path: 'collections1_1_4',
                    subMenu: [
                        {
                            id: 'id_1.1.4.1',
                            isActive: false,
                            name: '1.1.4.1',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_1_4_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.1.4.2',
                            isActive: false,
                            name: '1.1.4.2',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_1_4_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.1.4.3',
                            isActive: false,
                            name: '1.1.4.3',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_1_4_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.1.4.4',
                            isActive: false,
                            name: '1.1.4.4',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_1_4_4',
                            subMenu: null,
                        },
                    ],
                },
            ],
        },
        {
            id: 'id_Women', isActive: false, name: 'Women', prefixPath: 'products', level: 0, path: 'women', subMenu: [
                {
                    id: 'id_All', isActive: false, name: 'All', prefixPath: 'products',level: 1, path: 'all', subMenu: [
                        {
                            id: 'id_1.2.1.1',
                            isActive: false,
                            name: '1.2.1.1',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1.2.1.1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.1.2',
                            isActive: false,
                            name: '1.2.1.2',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1.2.1.2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.1.3',
                            isActive: false,
                            name: '1.2.1.3',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_1_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.1.4',
                            isActive: false,
                            name: '1.2.1.4',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_1_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_Women_Collections',
                    isActive: false,
                    name: 'Collections',
                    prefixPath: 'products',
                    level: 1,
                    path: 'collections',
                    subMenu: [
                        {
                            id: 'id_Our_Favorites',
                            isActive: false, name: 'Our Favorites',
                            prefixPath: 'products',
                            level: 2,
                            path: 'collections_our_favorites',
                            subMenu: null,
                        },
                        {
                            id: 'id_New_Arrivals',
                            isActive: false, name: 'New Arrivals',
                            prefixPath: 'products',
                            level: 2,
                            path: 'collections_new_arrivals',
                            subMenu: null,
                        },
                        {
                            id: 'id_New_Collections',
                            isActive: false, name: 'New Collections',
                            prefixPath: 'products',
                            level: 2,
                            path: 'collections_new_collections',
                            subMenu: null,
                        },
                        {
                            id: 'id_Brands',
                            isActive: false, name: 'Brands',
                            prefixPath: 'products',
                            level: 2,
                            path: 'collections_new_collections',
                            subMenu: [
                                {
                                    id: 'id_akris',
                                    isActive: false,
                                    name: 'Akris',
                                    prefixPath: 'products',
                                    level: 3,
                                    path: 'id_akris',
                                    subMenu: null,
                                },
                                {
                                    id: 'id_alice&olivia',
                                    isActive: false, name: 'Alice + Olivia',
                                    prefixPath: 'products',
                                    level: 3,
                                    path: 'id_alice&olivia',
                                    subMenu: null,
                                },
                                {
                                    id: 'id_brunello_cucinelli',
                                    isActive: false, name: 'Brunello Cucinelli',
                                    prefixPath: 'products',
                                    level: 3,
                                    path: 'id_brunello_cucinelli',
                                    subMenu: null,
                                },
                                {
                                    id: 'id_chanel',
                                    isActive: false,
                                    name: 'CHANEL',
                                    prefixPath: 'products',
                                    level: 3,
                                    path: 'id_chanel',
                                    subMenu: null,
                                },
                                {
                                    id: 'id_dolce&gabbana',
                                    isActive: false, name: 'Dolce & Gabbana',
                                    prefixPath: 'products',
                                    level: 3,
                                    path: 'id_dolce&gabbana',
                                    subMenu: null,
                                },
                                {
                                    id: 'id_eileen_fisher',
                                    isActive: false, name: 'Eileen Fisher',
                                    prefixPath: 'products',
                                    level: 3,
                                    path: 'id_eileen_fisher',
                                    subMenu: null,
                                },
                                {
                                    id: 'id_giorgio_armani',
                                    isActive: false, name: 'Giorgio Armani',
                                    prefixPath: 'products',
                                    level: 3,
                                    path: 'id_giorgio_armani',
                                    subMenu: null,
                                },
                                {
                                    id: 'id_gucci',
                                    isActive: false,
                                    name: 'Gucci',
                                    prefixPath: 'products',
                                    level: 3,
                                    path: 'id_gucci',
                                    subMenu: null,
                                },
                                {
                                    id: 'id_johnny_was',
                                    isActive: false, name: 'Johnny Was',
                                    prefixPath: 'products',
                                    level: 3,
                                    path: 'id_johnny_was',
                                    subMenu: null,
                                },
                                {
                                    id: 'id_lafayette_148_new_york',
                                    isActive: false, name: 'Lafayette 148 New York',
                                    prefixPath: 'products',
                                    level: 3,
                                    path: 'id_lafayette_148_new_york',
                                    subMenu: null,
                                },
                                {
                                    id: 'id_theory',
                                    isActive: false,
                                    name: 'Theory',
                                    prefixPath: 'products',
                                    level: 3,
                                    path: 'id_theory',
                                    subMenu: null,
                                },
                            ],
                        },
                        {
                            id: 'id_Trends',
                            isActive: false, name: 'Trends',
                            prefixPath: 'products',
                            level: 2,
                            path: 'collections_new_collections',
                            subMenu: null,
                        },
                        {
                            id: 'id_New_Names_at_Neiman`s',
                            isActive: false, name: 'New Names at Neiman`s',
                            prefixPath: 'products',
                            level: 2,
                            path: 'collections_new_collections',
                            subMenu: null,
                        },
                        {
                            id: 'id_luxe',
                            isActive: false,
                            name: 'Luxe',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_luxe',
                            subMenu: null,
                        },
                        {
                            id: 'id_essentials',
                            isActive: false, name: 'Essentials',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_essentials',
                            subMenu: null,
                        },
                        {
                            id: 'id_exclusives',
                            isActive: false, name: 'Exclusives',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_exclusives',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_Coats_&_Jackets',
                    isActive: false, name: 'Coats & Jackets',
                    prefixPath: 'products',
                    level: 1,
                    path: 'collections_coats_&_jackets',
                    subMenu: [
                        {
                            id: 'id_1.2.3.1',
                            isActive: false,
                            name: '1.2.3.1',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_3_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.3.2',
                            isActive: false,
                            name: '1.2.3.2',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_3_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.3.3',
                            isActive: false,
                            name: '1.2.3.3',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_3_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.3.4',
                            isActive: false,
                            name: '1.2.3.4',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_3_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_Dresses',
                    isActive: false,
                    name: 'Dresses',
                    prefixPath: 'products',
                    level: 1,
                    path: 'collections_presses',
                    subMenu: [
                        {
                            id: 'id_1.2.4.1',
                            isActive: false,
                            name: '1.2.4.1',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_4_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.4.2',
                            isActive: false,
                            name: '1.2.4.2',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_4_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.4.3',
                            isActive: false,
                            name: '1.2.4.3',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_4_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.4.4',
                            isActive: false,
                            name: '1.2.4.4',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_4_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_Pants',
                    isActive: false,
                    name: 'Pants',
                    prefixPath: 'products',
                    level: 1,
                    path: 'collections_pants',
                    subMenu: [
                        {
                            id: 'id_1.2.5.1',
                            isActive: false,
                            name: '1.2.5.1',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_5_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.5.2',
                            isActive: false,
                            name: '1.2.5.2',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_5_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.5.3',
                            isActive: false,
                            name: '1.2.5.3',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_5_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.5.4',
                            isActive: false,
                            name: '1.2.5.4',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_5_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_Jumpsuits_&_Rompers',
                    isActive: false, name: 'Jumpsuits & Rompers',
                    prefixPath: 'products',
                    level: 1,
                    path: 'collections_jumpsuits_&_rompers',
                    subMenu: [
                        {
                            id: 'id_1.2.6.1',
                            isActive: false,
                            name: '1.2.6.1',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_6_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.6.2',
                            isActive: false,
                            name: '1.2.6.2',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_6_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.6.3',
                            isActive: false,
                            name: '1.2.6.3',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_6_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.6.4',
                            isActive: false,
                            name: '1.2.6.4',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_6_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_Shorts',
                    isActive: false,
                    name: 'Shorts',
                    prefixPath: 'products',
                    level: 1,
                    path: 'collections_shorts',
                    subMenu: [
                        {
                            id: 'id_1.2.7.1',
                            isActive: false,
                            name: '1.2.7.1',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_7_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.7.2',
                            isActive: false,
                            name: '1.2.7.2',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_7_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.7.3',
                            isActive: false,
                            name: '1.2.7.3',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_7_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.7.4',
                            isActive: false,
                            name: '1.2.7.4',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_7_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_Skirts',
                    isActive: false,
                    name: 'Skirts',
                    prefixPath: 'products',
                    level: 1,
                    path: 'collections_skirts',
                    subMenu: [
                        {
                            id: 'id_1.2.8.1',
                            isActive: false,
                            name: '1.2.8.1',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_8_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.8.2',
                            isActive: false,
                            name: '1.2.8.2',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_8_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.8.3',
                            isActive: false,
                            name: '1.2.8.3',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_8_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.8.4',
                            isActive: false,
                            name: '1.2.8.4',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_8_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_Sweaters',
                    isActive: false,
                    name: 'Sweaters',
                    prefixPath: 'products',
                    level: 1,
                    path: 'collections_sweaters',
                    subMenu: [
                        {
                            id: 'id_1.2.9.1',
                            isActive: false,
                            name: '1.2.9.1',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_9_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.9.2',
                            isActive: false,
                            name: '1.2.9.2',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_9_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.9.3',
                            isActive: false,
                            name: '1.2.9.3',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_9_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.9.4',
                            isActive: false,
                            name: '1.2.9.4',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_9_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_Swimwear',
                    isActive: false,
                    name: 'Swimwear',
                    prefixPath: 'products',
                    level: 1,
                    path: 'collections_swimwear',
                    subMenu: [
                        {
                            id: 'id_1.2.10.1',
                            isActive: false,
                            name: '1.2.10.1',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_10_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.10.2',
                            isActive: false,
                            name: '1.2.10.2',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_10_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.10.3',
                            isActive: false,
                            name: '1.2.10.3',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_10_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.10.4',
                            isActive: false,
                            name: '1.2.10.4',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_10_3',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_Tops',
                    isActive: false,
                    name: 'Tops',
                    prefixPath: 'products',
                    level: 1,
                    path: 'collections_tops',
                    subMenu: [
                        {
                            id: 'id_1.2.11.1',
                            isActive: false,
                            name: '1.2.11.1',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_11_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.11.2',
                            isActive: false,
                            name: '1.2.11.2',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_11_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.11.3',
                            isActive: false,
                            name: '1.2.11.3',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_11_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.11.4',
                            isActive: false,
                            name: '1.2.11.4',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_11_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_Shoes',
                    isActive: false,
                    name: 'Shoes',
                    prefixPath: 'products',
                    level: 1,
                    path: 'collections_shoes',
                    subMenu: [
                        {
                            id: 'id_1.2.12.1',
                            isActive: false,
                            name: '1.2.12.1',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_12_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.12.2',
                            isActive: false,
                            name: '1.2.12.2',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_12_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.12.3',
                            isActive: false,
                            name: '1.2.12.3',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_12_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.2.12.4',
                            isActive: false,
                            name: '1.2.12.4',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_2_12_4',
                            subMenu: null,
                        },
                    ],
                },
            ],
        },
        {
            id: 'id_Kids', isActive: false, name: 'Kids', prefixPath: 'products',level: 0, path: 'kids', subMenu: [
                {
                    id: 'id_1.3.1',
                    isActive: false,
                    name: '1.3.1',
                    prefixPath: 'products',
                    level: 1,
                    path: 'collections_1_3_1',
                    subMenu: [
                        {
                            id: 'id_1.3.1.1',
                            isActive: false,
                            name: '1.3.1.1',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_3_1_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.3.1.2',
                            isActive: false,
                            name: '1.3.1.2',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_3_1_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.3.1.3',
                            isActive: false,
                            name: '1.3.1.3',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_3_1_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.3.1.4',
                            isActive: false,
                            name: '1.3.1.4',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_3_1_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_1.3.2',
                    isActive: false,
                    name: '1.3.2',
                    prefixPath: 'products',
                    level: 1,
                    path: 'collections_1_3_2',
                    subMenu: [
                        {
                            id: 'id_1.3.2.1',
                            isActive: false,
                            name: '1.3.2.1',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_3_2_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.3.2.2',
                            isActive: false,
                            name: '1.3.2.2',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_3_2_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.3.2.3',
                            isActive: false,
                            name: '1.3.2.3',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_3_2_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.3.2.4',
                            isActive: false,
                            name: '1.3.2.4',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_3_2_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_1.3.3',
                    isActive: false,
                    name: '1.3.3',
                    prefixPath: 'products',
                    level: 1,
                    path: 'collections_1_3_3',
                    subMenu: [
                        {
                            id: 'id_1.3.3.1',
                            isActive: false,
                            name: '1.3.3.1',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_3_3_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.3.3.2',
                            isActive: false,
                            name: '1.3.3.2',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_3_3_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.3.3.3',
                            isActive: false,
                            name: '1.3.3.3',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_3_3_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.3.3.4',
                            isActive: false,
                            name: '1.3.3.4',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_3_3_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_1.3.4',
                    isActive: false,
                    name: '1.3.4',
                    prefixPath: 'products',
                    level: 1,
                    path: 'collections_1_3_4',
                    subMenu: [
                        {
                            id: 'id_1.3.4.1',
                            isActive: false,
                            name: '1.3.4.1',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_3_4_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.3.4.2',
                            isActive: false,
                            name: '1.3.4.2',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_3_4_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.3.4.3',
                            isActive: false,
                            name: '1.3.4.3',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_3_4_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.3.4.4',
                            isActive: false,
                            name: '1.3.4.4',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_3_4_4',
                            subMenu: null,
                        },
                    ],
                },
            ],
        },
        {
            id: 'id_Sale', isActive: false, name: 'Sale', prefixPath: 'products',level: 0, path: 'sale', subMenu: [
                {
                    id: 'id_1.4.1',
                    isActive: false,
                    name: '1.4.1',
                    prefixPath: 'products',
                    level: 1,
                    path: 'collections_1_4_1',
                    subMenu: [
                        {
                            id: 'id_1.4.1.1',
                            isActive: false,
                            name: '1.4.1.1',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_4_1_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.4.1.2',
                            isActive: false,
                            name: '1.4.1.2',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_4_1_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.4.1.3',
                            isActive: false,
                            name: '1.4.1.3',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_4_1_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.4.1.4',
                            isActive: false,
                            name: '1.4.1.4',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_4_1_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_1.4.2',
                    isActive: false,
                    name: '1.4.2',
                    prefixPath: 'products',
                    level: 1,
                    path: 'collections_1_4_2',
                    subMenu: [
                        {
                            id: 'id_1.4.2.1',
                            isActive: false,
                            name: '1.4.2.1',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_4_2_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.4.2.2',
                            isActive: false,
                            name: '1.4.2.2',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_4_2_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.4.2.3',
                            isActive: false,
                            name: '1.4.2.3',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_4_2_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.4.2.4',
                            isActive: false,
                            name: '1.4.2.4',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_4_2_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_1.4.3',
                    isActive: false,
                    name: '1.4.3',
                    prefixPath: 'products',
                    level: 1,
                    path: 'collections_1_4_3',
                    subMenu: [
                        {
                            id: 'id_1.4.3.1',
                            isActive: false,
                            name: '1.4.3.1',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_4_3_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.4.3.2',
                            isActive: false,
                            name: '1.4.3.2',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_4_3_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.4.3.3',
                            isActive: false,
                            name: '1.4.3.3',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_4_3_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.4.3.4',
                            isActive: false,
                            name: '1.4.3.4',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_4_3_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_1.4.4',
                    isActive: false,
                    name: '1.4.4',
                    prefixPath: 'products',
                    level: 1,
                    path: 'collections_1_4_4',
                    subMenu: [
                        {
                            id: 'id_1.4.4.1',
                            isActive: false,
                            name: '1.4.4.1',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_4_4_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.4.4.2',
                            isActive: false,
                            name: '1.4.4.2',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_4_4_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.4.4.3',
                            isActive: false,
                            name: '1.4.4.3',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_4_4_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.4.4.4',
                            isActive: false,
                            name: '1.4.4.4',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_4_4_4',
                            subMenu: null,
                        },
                    ],
                },
            ],
        },
        {
            id: 'id_Collections',
            isActive: false,
            name: 'Collections',
            prefixPath: 'products',
            level: 0,
            path: 'collections',
            subMenu: [
                {
                    id: 'id_1.5.1',
                    isActive: false,
                    name: '1.5.1',
                    prefixPath: 'products',
                    level: 1,
                    path: 'collections_1_5_1',
                    subMenu: [
                        {
                            id: 'id_1.5.1.1',
                            isActive: false,
                            name: '1.5.1.1',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_5_1_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.5.1.2',
                            isActive: false,
                            name: '1.5.1.2',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_5_1_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.5.1.3',
                            isActive: false,
                            name: '1.5.1.3',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_5_1_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.5.1.4',
                            isActive: false,
                            name: '1.5.1.4',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_5_1_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_1.5.2',
                    isActive: false,
                    name: '1.5.2',
                    prefixPath: 'products',
                    level: 1,
                    path: 'collections_1_5_2',
                    subMenu: [
                        {
                            id: 'id_1.5.2.1',
                            isActive: false,
                            name: '1.5.2.1',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_5_2_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.5.2.2',
                            isActive: false,
                            name: '1.5.2.2',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_5_2_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.5.2.3',
                            isActive: false,
                            name: '1.5.2.3',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_5_2_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.5.2.4',
                            isActive: false,
                            name: '1.5.2.4',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_5_2_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_1.5.3',
                    isActive: false,
                    name: '1.5.3',
                    prefixPath: 'products',
                    level: 1,
                    path: 'collections_1_5_3',
                    subMenu: [
                        {
                            id: 'id_1.5.3.1',
                            isActive: false,
                            name: '1.5.3.1',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_5_3_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.5.3.2',
                            isActive: false,
                            name: '1.5.3.2',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_5_3_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.5.3.3',
                            isActive: false,
                            name: '1.5.3.3',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_5_3_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.5.3.4',
                            isActive: false,
                            name: '1.5.3.4',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_5_3_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_1.5.4',
                    isActive: false,
                    name: '1.5.4',
                    prefixPath: 'products',
                    level: 1,
                    path: 'collections_1_5_4',
                    subMenu: [
                        {
                            id: 'id_1.5.4.1',
                            isActive: false,
                            name: '1.5.4.1',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_5_4_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.5.4.2',
                            isActive: false,
                            name: '1.5.4.2',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_5_4_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.5.4.3',
                            isActive: false,
                            name: '1.5.4.3',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_5_4_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.5.4.4',
                            isActive: false,
                            name: '1.5.4.4',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_5_4_4',
                            subMenu: null,
                        },
                    ],
                },
            ],
        },
        {
            id: 'id_Blog', isActive: false, name: 'Blog', prefixPath: 'products',level: 0, path: 'blog', subMenu: [
                {
                    id: 'id_1.6.1',
                    isActive: false,
                    name: '1.6.1',
                    prefixPath: 'products',
                    level: 1,
                    path: 'collections_1_6_1',
                    subMenu: [
                        {
                            id: 'id_1.6.1.1',
                            isActive: false,
                            name: '1.6.1.1',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_6_1_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.6.1.2',
                            isActive: false,
                            name: '1.6.1.2',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_6_1_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.6.1.3',
                            isActive: false,
                            name: '1.6.1.3',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_6_1_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.6.1.4',
                            isActive: false,
                            name: '1.6.1.4',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_6_1_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_1.6.2',
                    isActive: false,
                    name: '1.6.2',
                    prefixPath: 'products',
                    level: 1,
                    path: 'collections_1_6_2',
                    subMenu: [
                        {
                            id: 'id_1.6.2.1',
                            isActive: false,
                            name: '1.6.2.1',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_6_2_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.6.2.2',
                            isActive: false,
                            name: '1.6.2.2',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_6_2_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.6.2.3',
                            isActive: false,
                            name: '1.6.2.3',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_6_2_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.6.2.4',
                            isActive: false,
                            name: '1.6.2.4',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_6_2_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_1.6.3',
                    isActive: false,
                    name: '1.6.3',
                    prefixPath: 'products',
                    level: 1,
                    path: 'collections_1_6_3',
                    subMenu: [
                        {
                            id: 'id_1.6.3.1',
                            isActive: false,
                            name: '1.6.3.1',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_6_3_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.6.3.2',
                            isActive: false,
                            name: '1.6.3.2',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_6_3_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.6.3.3',
                            isActive: false,
                            name: '1.6.3.3',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_6_3_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.6.3.4',
                            isActive: false,
                            name: '1.6.3.4',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_6_3_4',
                            subMenu: null,
                        },
                    ],
                },
                {
                    id: 'id_1.6.4',
                    isActive: false,
                    name: '1.6.4',
                    prefixPath: 'products',
                    level: 1,
                    path: 'collections_1_6_4',
                    subMenu: [
                        {
                            id: 'id_1.6.4.1',
                            isActive: false,
                            name: '1.6.4.1',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_6_4_1',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.6.4.2',
                            isActive: false,
                            name: '1.6.4.2',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_6_4_2',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.6.4.3',
                            isActive: false,
                            name: '1.6.4.3',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_6_4_3',
                            subMenu: null,
                        },
                        {
                            id: 'id_1.6.4.4',
                            isActive: false,
                            name: '1.6.4.4',
                            prefixPath: 'products',
                            level: 2,
                            path: 'id_1_6_4_4',
                            subMenu: null,
                        },
                    ],
                },
            ],
        },
    ],
};